export const methods = [
  {
    id: "insertion",
    name: "Insertion Sort",
    description: "It is insertion sort",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },
  {
    id: "bubble",
    name: "Bubble Sort",
    description: "It is bubble sort",
    timeComplexity: "O(n^2)",
    spaceComplexity: "O(n)",
  },
  {
    id: "merge",
    name: "Merge Sort",
    description: "It is merge sort",
    timeComplexity: "O(nlog(n))",
    spaceComplexity: "O(n)",
  },
  {
    id: "heap",
    name: "Heap Sort",
    description: "It is Heap sort",
    timeComplexity: "O(nlog(n))",
    spaceComplexity: "O(n)",
  },
  {
    id: "quick",
    name: "Quick Sort",
    description: "It is Quick sort",
    timeComplexity: "O(n*log(n))",
    spaceComplexity: "O(n*log(n))",
  },
  {
    id: "radix",
    name: "Radix Sort",
    description: "It is Radix sort",
    timeComplexity: "O(nd)",
    spaceComplexity: "O(n+2^d)",
  },
  {
    id: "bucket",
    name: "Bucket Sort",
    description: "It is Bucket sort",
    timeComplexity: "O(n^2)",
    spaceComplexity: "O(n^2)",
  },
  {
    id: "counting",
    name: "Counting Sort",
    description: "It is Counting sort",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
  },
  {
    id: "modifiedQuick",
    name: "Modified Quick Sort (7.4.5)",
    description: "It is Modified Quick sort",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
  },
  {
    id: "boundedCount",
    name: "Bounded Count Sort (8.2.4)",
    description: "It is Bounded Count sort",
    timeComplexity: "O(k)",
    spaceComplexity: "O(k)",
  },
];
